# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60025981c0934da989bfbaf05800f182"
name = "HC Shelf Label POS"
handle = "hc-shelf-label-pos"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
