# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0a6ea062f34d7b8855ad362ee69b859e"
application_url = "https://compliant-css-proof-minutes.trycloudflare.com"
embedded = true
name = "Print shelf label"
handle = "hotwax-shelf-label-pos"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://compliant-css-proof-minutes.trycloudflare.com/auth/callback", "https://compliant-css-proof-minutes.trycloudflare.com/auth/shopify/callback", "https://compliant-css-proof-minutes.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
